# Generated by Django 4.0.3 on 2022-03-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_students_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
